CREATE DATABASE droast;
USE droast;
CREATE TABLE roasts(
	id INT AUTO_INCREMENT PRIMARY KEY,
	image_link VARCHAR (255) NOT NULL,
	post_title VARCHAR (255) NOT NULL,
	c1 TEXT NOT NULL,
	c2 TEXT NOT NULL,
	c3 TEXT NOT NULL,
	c4 TEXT NOT NULL,
	c5 TEXT NOT NULL,
	c6 TEXT NOT NULL
);
